name = "ba-gift-planner"
main = "src/worker.js" 
compatibility_date = "2026-07-01"

[assets]
directory = "dist"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "ba-gift-planner-db"
database_id = "d57f4aa9-7a63-4a68-a113-ffe77c781dab"

[vars]
ENVIRONMENT = "production"
